# .cargo/config.toml
#
[env]
DEFMT_LOG="info"

# Cannot steer 'target', can we? tbd.
#
#[build.'cfg(feature = "eps32c3")']
#target    = "riscv32imc-unknown-none-elf"
#[build.'cfg(feature = "eps32c6")']
#target    = "riscv32imac-unknown-none-elf"

[build]
rustflags = [
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-arg=-Tlinkall.x",
  # NOTE: This is required to obtain backtraces, however it may negatively
  #       impact the performance of your application.
  "-C", "force-frame-pointers",
]

[target.riscv32imac-unknown-none-elf]
runner = "probe-rs run --chip=esp32c6"

[unstable]
build-std = ["core"]
