# .cargo/config.toml
#
[env]
DEFMT_LOG="info"

# Cannot steer 'target'
#
#[build.'cfg(feature = "eps32c3")']
#target    = "riscv32imc-unknown-none-elf"
#[build.'cfg(feature = "eps32c6")']
#target    = "riscv32imac-unknown-none-elf"

[build]
rustflags = [
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-arg=-Tlinkall.x",

  # NOTE: Required to obtain backtraces, however it may negatively impact the performance of your application.
  "-C", "force-frame-pointers",
]

#R[target]
#Rrunner = "probe-rs run --chip xxx"

[unstable]
build-std = ["core"]
